projectTitle = "TheShipPostMod"
modId = "shippost"
githubRepo = "TeamVoided/TheShippostMod"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "Ender", "Astra", "Dusk", "Deathlord"  ]
majorMinecraftVersion = "1.20"
minecraftVersion = "1.20.5-rc2"
fabricLoaderVersion = "0.15.10"
fabricApiVersion = "0.97.4+1.20.5"
fabricLangKotlinVersion = "1.10.19+kotlin.1.9.23"
license = "MIT"
modules = [  ]

[mappings]
    # You have 6 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    type = "QUILT"
    version = "1.20.5-rc2+build.3"