projectTitle = "TheShipPostMod"
modId = "shippost"
githubRepo = "TeamVoided/TheShippostMod"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "TheEnderCore", "Astra", "Dusk", "Deathlord"  ]
majorMinecraftVersion = "1.21"
minecraftVersion = "1.21"
fabricLoaderVersion = "0.15.11"
fabricApiVersion = "0.100.1+1.21"
fabricLangKotlinVersion = "1.11.0+kotlin.2.0.0"
license = "MIT"
modules = [  ]
modDescription = "The silliest and the goofiest features you count ever want in this game."
# Modmenu badges, values can be: [ library, deprecated ]
badges = [ ]
disableKotlin = false

[mappings]
    # You have 6 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    type = "QUILT"
    version = "1.21+build.2"